Repository Toua45/Dame-Jeanne, pull requests merged in 2020-05, with the labels that each got.

#163 fix product
  src/Controller/AdminProductController.php
  src/Controller/ProductController.php
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
  templates/admin_section_product/_delete_form.html.twig
  templates/admin_section_product/_form.html.twig
  templates/admin_section_product/edit.html.twig
  templates/admin_section_product/index.html.twig
  templates/admin_section_product/show.html.twig
  templates/product/index.html.twig
  templates/product/show.html.twig
Labels: need reviewed

#166 Pagination
  assets/css/app.scss
  assets/css/pagination.scss
  assets/css/style_article.scss
  src/Controller/BlogController.php
  src/Controller/ProductController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/ProductFixtures.php
  templates/blog/index.html.twig
  templates/pagination/blog_pagination.html.twig
  templates/pagination/products_pagination.html.twig
  templates/product/index.html.twig
Labels: reviewed

#169 fix about link blog on navbar
  templates/_navbar.html.twig
Labels: reviewed

#170 fixture about coordinate
  src/DataFixtures/CoordinateFixtures.php
Labels: reviewed

#171 add flash messages
  src/Controller/AdminMessageController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminProductController.php
  src/Controller/AdminSectionController.php
  src/Controller/AdminTeamController.php
  src/Entity/Section.php
  templates/admin_product/index.html.twig
  templates/admin_section_product/_delete_form.html.twig
Labels: need reviewed

#176 fix product
  src/Entity/Product.php
Labels: need reviewed, reviewed

#177 fix affichage product et team
  assets/css/app.scss
  assets/css/partners.scss
  assets/css/style_product.scss
  assets/images/food.webp
  assets/images/patron-bis.webp
  assets/images/taste.webp
  src/Controller/PresentationController.php
  src/DataFixtures/MessageFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/TeamFixtures.php
  templates/_navbar_admin.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_team/index.html.twig
  templates/message/index.html.twig
  templates/presentation/_message.html.twig
  templates/presentation/_partner.html.twig
  templates/presentation/_team.html.twig
  templates/presentation/index.html.twig
  templates/product/index.html.twig
  templates/product/show.html.twig
Labels: reviewed
