Repository Toua45/Dame-Jeanne, pull requests merged in 2020-03, with the labels that each got.

#106 Affichage des produits
  config/packages/framework.yaml
  src/Controller/AdminProductController.php
  src/Controller/AdminSectionController.php
  src/Controller/ProductController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Product.php
  src/Entity/Section.php
  src/Form/ProductType.php
  src/Form/SectionType.php
  src/Repository/ProductRepository.php
  src/Repository/SectionRepository.php
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
  templates/admin_section/_delete_form.html.twig
  templates/admin_section/_form.html.twig
  templates/admin_section/edit.html.twig
  templates/admin_section/index.html.twig
  templates/admin_section/new.html.twig
  templates/admin_section/show.html.twig
  templates/product/index.html.twig
Labels: reviewed

#108 paging articles on index
  src/Controller/BlogController.php
  src/DataFixtures/ArticleFixtures.php
  src/Repository/ArticleRepository.php
  templates/blog/index.html.twig
  templates/blog/show.html.twig
  templates/home/include/_article.html.twig
Labels: reviewed

#109 S02 admin navbar
  templates/_navbar_admin.html.twig
  templates/layout_admin.html.twig
Labels: reviewed

#110 CSS admin produit et section OK
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
  templates/admin_section/_delete_form.html.twig
  templates/admin_section/_form.html.twig
  templates/admin_section/edit.html.twig
  templates/admin_section/index.html.twig
  templates/admin_section/new.html.twig
  templates/admin_section/show.html.twig
Labels: reviewed

#113 system upload product OK
  .gitignore
  config/packages/vich_uploader.yaml
  src/Entity/Product.php
  src/Form/ProductType.php
Labels: reviewed

#118 So2 us13 data verification category and articles
  src/Entity/Article.php
  src/Entity/Category.php
Labels: reviewed

#119 validation of coordinate realised
  src/Entity/Coordinate.php
Labels: reviewed

#123 Routes security
  config/packages/security.yaml
  src/Controller/AdminArticleController.php
  src/Controller/AdminCategoryController.php
  src/Controller/AdminCoordinateController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminProductController.php
  src/Controller/AdminSectionController.php
Labels: reviewed

#122 Add flash messages - admin
  src/Controller/AdminArticleController.php
  src/Controller/AdminCategoryController.php
  src/Controller/AdminCoordinateController.php
  src/Controller/AdminSectionController.php
  templates/layout_admin.html.twig
Labels: need reviewed

#120 fixtures product and section OK
  src/DataFixtures/ProductFixtures.php
  src/DataFixtures/SectionFixtures.php
Labels: need reviewed

#124 affichage produits
  src/Controller/AdminProductController.php
  src/Controller/ProductController.php
  src/DataFixtures/ProductFixtures.php
  src/DataFixtures/SectionFixtures.php
  src/Form/ProductSearchType.php
  src/Repository/ProductRepository.php
  templates/_navbar.html.twig
  templates/_navbar_admin.html.twig
  templates/product/index.html.twig
Labels: reviewed

#127 modal product
  src/Entity/Product.php
  templates/product/index.html.twig
Labels: reviewed

#128 modif route admin index product
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
Labels: reviewed

#129 Admin modal home page
  assets/css/_navbar_style.scss
  src/Controller/HomeController.php
  templates/_navbar.html.twig
  templates/security/login.html.twig
Labels: reviewed

#130 Redirect admin navbar
  src/Controller/HomeController.php
  templates/_navbar.html.twig
  templates/_navbar_admin.html.twig
Labels: Priority !, need reviewed

#151 fix upload et orthographe coordinatetype
  src/Form/ArticleType.php
  src/Form/CoordinateType.php
  src/Form/ProductType.php
  symfony.lock
  templates/admin_product/index.html.twig
  templates/admin_product/show.html.twig
Labels: reviewed

#154 Us05 navbar admin
  templates/_navbar_admin.html.twig
Labels: need reviewed

#156 modif icons product and product section
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
  templates/admin_section_product/_delete_form.html.twig
  templates/admin_section_product/_form.html.twig
  templates/admin_section_product/edit.html.twig
  templates/admin_section_product/index.html.twig
  templates/admin_section_product/new.html.twig
  templates/admin_section_product/show.html.twig
  templates/product/index.html.twig
Labels: reviewed

#158 Add icons in navbar admin
  symfony.lock
  templates/_navbar_admin.html.twig
Labels: Priority !, need reviewed
